version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: crm  # Añade esta línea
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro  # Script de inicialización
      - ./crm_data.json:/tmp/crm_data.json:ro  # Tu archivo de datos

volumes:
  mongo_data: